from __future__ import annotations

from dataclasses import dataclass

from krrood.exceptions import DataclassException


class DontPrintStackTrace:
    """
    Marker mixin for exceptions whose stack trace should not be printed.
    """


@dataclass
class GiskardException(DataclassException):
    """
    Base class for all errors raised by Giskard.
    """


@dataclass
class SetupException(GiskardException):
    """
    Base class for errors that occur while configuring Giskard.
    """


@dataclass
class PlanningException(GiskardException):
    """
    Base class for errors that occur while planning a motion.
    """


@dataclass
class DegreeOfFreedomNotRecordedError(GiskardException):
    """
    Raised when a recorded world-state trajectory does not contain a requested degree of
    freedom.
    """

    connection_name: str
    """
    The name of the connection whose degree of freedom was requested.
    """

    def error_message(self) -> str:
        return (
            f"The recorded world-state trajectory contains no positions for the degree of "
            f"freedom of connection '{self.connection_name}'."
        )

    def suggest_correction(self) -> str:
        return "make sure the connection is part of the simulated world before running the physics model."


@dataclass
class WorldNotEmptyError(SetupException):
    """
    Raised when a world config that must build its world from scratch is run on a world
    that already contains kinematic structure.
    """

    config_name: str
    """The name of the world config class that requires an empty world."""

    def error_message(self) -> str:
        return f"{self.config_name} requires an empty world to set up."

    def suggest_correction(self) -> str:
        return "Run setup_world() before adding anything else to the world."


@dataclass
class HandleActuatorMismatchError(SetupException):
    """
    Raised when a container handle is not driven by the actuator a physics model was
    configured with, so the resulting motion would move a different joint than the one
    being recorded.
    """

    handle_name: str
    """The name of the handle body."""

    actuator_name: str
    """
    The name of the configured actuator connection.
    """

    handle_connection_name: str
    """The name of the 1-DOF connection that actually drives the handle."""

    def error_message(self) -> str:
        return (
            f"Handle '{self.handle_name}' is driven by connection "
            f"'{self.handle_connection_name}', not by the configured actuator "
            f"'{self.actuator_name}'."
        )

    def suggest_correction(self) -> str:
        return "Pass the ActiveConnection1DOF that drives the handle as the actuator."


@dataclass
class MissingActionResultError(GiskardException):
    """
    Raised when a result message is requested before one has been set.
    """

    def error_message(self) -> str:
        return "No result message set."

    def suggest_correction(self) -> str:
        return "You tried to access something before it was set."


@dataclass
class DuplicateNameException(GiskardException):
    """
    Raised when a name that must be unique is used more than once.
    """

    name: str
    """
    The name that already exists.
    """

    def error_message(self) -> str:
        return f'A constraint named "{self.name}" already exists.'

    def suggest_correction(self) -> str:
        return "Node names of Motion Statecharts are autogenerated. You are likely setting names manually. Don't do that if you don't care about names."


@dataclass
class NoControlledJointsError(SetupException):
    """
    Raised when no joint is flagged as controlled.
    """

    def error_message(self) -> str:
        return "No joints are flagged as controlled."

    def suggest_correction(self) -> str:
        return "Make sure robot_interface_config of Giskard is setup correctly."


@dataclass
class JointRegistrationRequiresStandaloneModeError(SetupException):
    """
    Raised when joints are registered outside of StandAlone mode.
    """

    def error_message(self) -> str:
        return "Joints only need to be registered in StandAlone mode."

    def suggest_correction(self) -> str:
        return "Remove the manual registration. For real robots, the joints are retrieved from the connected controllers."


@dataclass
class MaxTrajectoryLengthException(PlanningException):
    """
    Raised when a planned trajectory exceeds the maximum allowed length.
    """

    def error_message(self) -> str:
        return "Trajectory exceeded the maximum allowed length."

    def suggest_correction(self) -> str:
        return "Look at the final state of the MotionStatechart to see which nodes are still running. Use the debugger or the MotionStatechart.draw() method to visualize the MotionStatechart."


@dataclass
class SelfCollisionViolatedException(PlanningException):
    """
    Raised when a self-collision constraint is violated during planning.
    """

    def error_message(self) -> str:
        return "A self-collision constraint was violated during planning."

    def suggest_correction(self) -> str:
        return ""
