from __future__ import annotations
from dataclasses import dataclass

from typing_extensions import List, Iterator

from semantic_digital_twin.spatial_types.spatial_types import Pose


@dataclass
class BaseLocation:
    """
    Base for all locations that can be used to plan movements.
    """

    generator: PoseGeneratorBackend
    """
    Backend that generates pose candidates.
    """
    validators: List[PoseValidator]
    """
    Validators that are used to check if a generated pose is valid.
    """

    def __iter__(self) -> Iterator[Pose]:
        for pose_candidate in self.generator:
            if all(validator(pose_candidate) for validator in self.validators):
                yield pose_candidate

    def merge(self, other: BaseLocation) -> BaseLocation:
        """
        Merge this location with another location, merging the generator backends and validators.

        :param other: The other location to merge with.
        :return: A new location that is the merge of this location and the other location.
        """
        return BaseLocation(
            self.generator.merge(other.generator), self.validators + other.validators
        )

    def __and__(self, other: BaseLocation) -> BaseLocation:
        return self.merge(other)


@dataclass
class PoseGeneratorBackend:
    """
    Generator backend base class for poses, generates pose candidates which are checked against a set of validators.
    """

    def __iter__(self) -> Iterator[Pose]:
        pass

    def merge(self, other: PoseGeneratorBackend) -> PoseGeneratorBackend:
        """
        Merge this pose generator backend with another pose generator backend. The resulting pose generator backend
        generates pose candidates that are generated by both pose generator backends.

        :param other: The other pose generator backend to merge with.
        :return: A new pose generator backend that is the merge of this pose generator backend and the other pose generator backend.
        """
        pass

    def __and__(self, other: PoseGeneratorBackend) -> PoseGeneratorBackend:
        return self.merge(other)


@dataclass
class PoseValidator:
    """
    Validates a pose candidate.
    """

    def __call__(self, pose: Pose) -> bool:
        pass
